language: java
sudo: required
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
jdk:
  - oraclejdk7
before_install:
 - chmod +x gradlew
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
