-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2015-04-13 15:38:20.844

SET AUTOCOMMIT TRUE;
-- tables
-- Table: Task
CREATE TABLE TodoTasks (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	description varchar(255)  NULL,
    listorder int  NULL,
    createdon timestamp  NULL,
    completedon timestamp  NULL,
   CONSTRAINT TodoTasks_pk PRIMARY KEY (id)
);




